AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/bundle/**/**

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/**/*

Style/Documentation:
  Enabled: true
  Exclude: 
    - db/migrate/*
    - config/application.rb
